name: TilliaManager
version: 1.0.0
main: xyz.volartrix.TilliaManagerPlugin
description: Tillia Server Manager Plugin
author: NotNekodev
website: https://papermc.io
api-version: '1.21.4'

depend: ["PlaceholderAPI", "LuckPerms"]

commands:
  tempban:
    description: Temporarily bans a player
    permission-message: You do not have permission to use this command.
    permission: bozo.tempban
  unban:
    description: Unbans a player
    permission-message: You do not have permission to use this command.
    permission: bozo.unban
    aliases:
      - pardon
  ban:
    description: Bans a player
    permission-message: You do not have permission to use this command.
    permission: bozo.ban
  staffchat:
    description: Sends a message to all staff members
    permission-message: You do not have permission to use this command.
    permission: bozo.staffchat
    aliases:
      - sc
  tp2p:
    description: Teleports a player to another player
    permission-message: You do not have permission to use this command.
    permission: bozo.tp2p
    aliases:
      - tptop
      - tptoplayer
      - teleport2player
  spawn:
    description: Teleports a player to the spawn
    permission-message: You do not have permission to use this command.
    permission: bozo.spawn